baseURL = "https://yapkke.github.io/"
languageCode = 'en-us'
title = "Yup I'm Yap"
theme = 'zen'

[outputs]
  home = ["HTML", "RSS", "FlexSearch"]

[outputFormats.FlexSearch]
  mediaType = "application/json"
  baseName = "flexsearch"
